from app import models


REAL_ITEMS = [
    # ── Web Servers ──────────────────────────────────────────────────────────
    {
        "name": "nginx", "item_type": "application", "category": "Web Server",
        "manufacturer": "F5 Inc", "developer": "Igor Sysoev", "version": "1.25.3",
        "description": "High-performance HTTP server and reverse proxy",
        "components": [
            ("openssl", "3.0.11", "OpenSSL Foundation", "Apache-2.0"),
            ("pcre2", "10.42", "PCRE2 Project", "BSD-2-Clause"),
            ("zlib", "1.3.1", "Jean-loup Gailly", "Zlib"),
            ("libcrypto", "3.0.11", "OpenSSL Foundation", "Apache-2.0"),
            ("libssl", "3.0.11", "OpenSSL Foundation", "Apache-2.0"),
            ("glibc", "2.38", "GNU Project", "LGPL-2.1"),
            ("libpthread", "2.38", "GNU Project", "LGPL-2.1"),
            ("libm", "2.38", "GNU Project", "LGPL-2.1"),
        ],
    },
    {
        "name": "Apache HTTP Server", "item_type": "application", "category": "Web Server",
        "manufacturer": "Apache Software Foundation", "developer": "Apache Software Foundation", "version": "2.4.58",
        "description": "World's most popular web server software",
        "components": [
            ("openssl", "3.0.11", "OpenSSL Foundation", "Apache-2.0"),
            ("apr", "1.7.4", "Apache Software Foundation", "Apache-2.0"),
            ("apr-util", "1.6.3", "Apache Software Foundation", "Apache-2.0"),
            ("pcre2", "10.42", "PCRE2 Project", "BSD-2-Clause"),
            ("zlib", "1.3.1", "Jean-loup Gailly", "Zlib"),
            ("libxml2", "2.11.5", "GNOME Project", "MIT"),
            ("lua", "5.4.6", "PUC-Rio", "MIT"),
            ("expat", "2.5.0", "Expat Project", "MIT"),
            ("libcurl", "8.4.0", "Daniel Stenberg", "curl"),
        ],
    },
    {
        "name": "HAProxy", "item_type": "application", "category": "Load Balancer",
        "manufacturer": "HAProxy Technologies", "developer": "Willy Tarreau", "version": "2.8.5",
        "description": "Reliable high-performance TCP/HTTP load balancer",
        "components": [
            ("openssl", "3.0.11", "OpenSSL Foundation", "Apache-2.0"),
            ("pcre2", "10.42", "PCRE2 Project", "BSD-2-Clause"),
            ("lua", "5.4.6", "PUC-Rio", "MIT"),
            ("libslz", "1.2.1", "Willy Tarreau", "MIT"),
            ("zlib", "1.3.1", "Jean-loup Gailly", "Zlib"),
            ("libsystemd", "254", "systemd Project", "LGPL-2.1"),
        ],
    },
    {
        "name": "Caddy", "item_type": "application", "category": "Web Server",
        "manufacturer": "Stack Holdings GmbH", "developer": "Matt Holt", "version": "2.7.6",
        "description": "Fast, multi-platform web server with automatic HTTPS",
        "components": [
            ("golang", "1.21.3", "Google LLC", "BSD-3-Clause"),
            ("golang.org/x/net", "0.17.0", "Google LLC", "BSD-3-Clause"),
            ("golang.org/x/crypto", "0.14.0", "Google LLC", "BSD-3-Clause"),
            ("go-acme/lego", "4.14.2", "go-acme", "MIT"),
            ("gorilla/mux", "1.8.1", "Gorilla Web Toolkit", "BSD-3-Clause"),
            ("mholt/acmez", "1.2.0", "Matt Holt", "Apache-2.0"),
            ("zap", "1.26.0", "Uber Technologies", "MIT"),
        ],
    },
    # ── Databases ────────────────────────────────────────────────────────────
    {
        "name": "PostgreSQL", "item_type": "application", "category": "Database",
        "manufacturer": "PostgreSQL Global Development Group", "developer": "PostgreSQL Global Development Group", "version": "16.1",
        "description": "Advanced open source relational database",
        "components": [
            ("openssl", "3.0.11", "OpenSSL Foundation", "Apache-2.0"),
            ("readline", "8.2", "Free Software Foundation", "GPL-3.0"),
            ("zlib", "1.3.1", "Jean-loup Gailly", "Zlib"),
            ("libxml2", "2.11.5", "GNOME Project", "MIT"),
            ("icu", "73.2", "Unicode Consortium", "Unicode-DFS-2016"),
            ("krb5", "1.21.2", "MIT Kerberos Team", "MIT"),
            ("pam", "1.5.3", "Linux-PAM Project", "GPL-2.0"),
            ("systemd", "254", "systemd Project", "LGPL-2.1"),
            ("libldap", "2.6.6", "OpenLDAP Foundation", "OLDAP-2.8"),
        ],
    },
    {
        "name": "MySQL", "item_type": "application", "category": "Database",
        "manufacturer": "Oracle Corporation", "developer": "Oracle Corporation", "version": "8.2.0",
        "description": "World's most popular open source database",
        "components": [
            ("openssl", "3.0.11", "OpenSSL Foundation", "Apache-2.0"),
            ("boost", "1.77.0", "Boost Community", "BSL-1.0"),
            ("libedit", "3.1", "NetBSD Project", "BSD-3-Clause"),
            ("zlib", "1.3.1", "Jean-loup Gailly", "Zlib"),
            ("protobuf", "3.21.12", "Google LLC", "BSD-3-Clause"),
            ("icu", "73.2", "Unicode Consortium", "Unicode-DFS-2016"),
            ("libevent", "2.1.12", "Niels Provos", "BSD-3-Clause"),
            ("rapidjson", "1.1.0", "Tencent", "MIT"),
            ("lz4", "1.9.4", "Yann Collet", "BSD-2-Clause"),
        ],
    },
    {
        "name": "Redis", "item_type": "application", "category": "Cache Database",
        "manufacturer": "Redis Ltd", "developer": "Salvatore Sanfilippo", "version": "7.2.3",
        "description": "In-memory data structure store used as cache and message broker",
        "components": [
            ("jemalloc", "5.3.0", "Jason Evans", "BSD-2-Clause"),
            ("hiredis", "1.2.0", "Redis Ltd", "BSD-3-Clause"),
            ("linenoise", "1.0", "Salvatore Sanfilippo", "BSD-2-Clause"),
            ("lua", "5.1.5", "PUC-Rio", "MIT"),
            ("openssl", "3.0.11", "OpenSSL Foundation", "Apache-2.0"),
            ("libsystemd", "254", "systemd Project", "LGPL-2.1"),
            ("lz4", "1.9.4", "Yann Collet", "BSD-2-Clause"),
        ],
    },
    {
        "name": "MongoDB", "item_type": "application", "category": "NoSQL Database",
        "manufacturer": "MongoDB Inc", "developer": "MongoDB Inc", "version": "7.0.4",
        "description": "General purpose document-oriented database",
        "components": [
            ("openssl", "3.0.11", "OpenSSL Foundation", "Apache-2.0"),
            ("boost", "1.80.0", "Boost Community", "BSL-1.0"),
            ("snappy", "1.1.10", "Google LLC", "BSD-3-Clause"),
            ("zlib", "1.3.1", "Jean-loup Gailly", "Zlib"),
            ("zstd", "1.5.5", "Meta Platforms Inc", "BSD-3-Clause"),
            ("pcre2", "10.42", "PCRE2 Project", "BSD-2-Clause"),
            ("wiredtiger", "11.2.0", "MongoDB Inc", "NOASSERTION"),
            ("asio", "1.28.0", "Christopher Kohlhoff", "BSL-1.0"),
            ("fmt", "9.1.0", "Victor Zverovich", "MIT"),
            ("libstemmer", "2.2.0", "Snowball Project", "BSD-3-Clause"),
        ],
    },
    {
        "name": "SQLite", "item_type": "application", "category": "Embedded Database",
        "manufacturer": "D. Richard Hipp", "developer": "D. Richard Hipp", "version": "3.43.2",
        "description": "Self-contained, serverless, zero-configuration SQL database engine",
        "components": [
            ("tcl", "8.6.13", "Regents of UCB", "TCL"),
            ("zlib", "1.3.1", "Jean-loup Gailly", "Zlib"),
            ("libc", "2.38", "GNU Project", "LGPL-2.1"),
        ],
    },
    {
        "name": "MariaDB", "item_type": "application", "category": "Database",
        "manufacturer": "MariaDB Foundation", "developer": "MariaDB Foundation", "version": "11.2.2",
        "description": "Community-developed fork of MySQL relational database",
        "components": [
            ("openssl", "3.0.11", "OpenSSL Foundation", "Apache-2.0"),
            ("zlib", "1.3.1", "Jean-loup Gailly", "Zlib"),
            ("pcre2", "10.42", "PCRE2 Project", "BSD-2-Clause"),
            ("jemalloc", "5.3.0", "Jason Evans", "BSD-2-Clause"),
            ("lz4", "1.9.4", "Yann Collet", "BSD-2-Clause"),
            ("snappy", "1.1.10", "Google LLC", "BSD-3-Clause"),
            ("libxml2", "2.11.5", "GNOME Project", "MIT"),
            ("rocksdb", "8.6.7", "Meta Platforms Inc", "Apache-2.0"),
        ],
    },
    {
        "name": "Elasticsearch", "item_type": "application", "category": "Search Engine",
        "manufacturer": "Elastic NV", "developer": "Elastic NV", "version": "8.11.1",
        "description": "Distributed RESTful search and analytics engine",
        "components": [
            ("java", "21.0.1", "Eclipse Adoptium", "GPL-2.0"),
            ("lucene", "9.8.0", "Apache Software Foundation", "Apache-2.0"),
            ("netty", "4.1.100", "Netty Project", "Apache-2.0"),
            ("jackson", "2.15.3", "FasterXML", "Apache-2.0"),
            ("log4j2", "2.21.1", "Apache Software Foundation", "Apache-2.0"),
            ("snappy", "1.1.10.5", "Google LLC", "BSD-3-Clause"),
            ("bouncycastle", "1.77", "Legion of the Bouncy Castle", "MIT"),
            ("jna", "5.13.0", "GitHub", "Apache-2.0"),
        ],
    },
    {
        "name": "Cassandra", "item_type": "application", "category": "NoSQL Database",
        "manufacturer": "Apache Software Foundation", "developer": "Apache Software Foundation", "version": "4.1.3",
        "description": "Highly scalable distributed NoSQL database",
        "components": [
            ("java", "11.0.21", "Eclipse Adoptium", "GPL-2.0"),
            ("netty", "4.1.100", "Netty Project", "Apache-2.0"),
            ("guava", "32.1.3", "Google LLC", "Apache-2.0"),
            ("jackson", "2.15.3", "FasterXML", "Apache-2.0"),
            ("snappy", "1.1.10", "Google LLC", "BSD-3-Clause"),
            ("lz4", "1.9.4", "Yann Collet", "BSD-2-Clause"),
            ("slf4j", "2.0.9", "QOS.ch", "MIT"),
            ("antlr4", "4.13.1", "Terence Parr", "BSD-3-Clause"),
        ],
    },
    # ── Container & Orchestration ────────────────────────────────────────────
    {
        "name": "Docker Engine", "item_type": "application", "category": "Container Runtime",
        "manufacturer": "Docker Inc", "developer": "Docker Inc", "version": "24.0.7",
        "description": "Container platform for building and running applications",
        "components": [
            ("containerd", "1.7.8", "CNCF", "Apache-2.0"),
            ("runc", "1.1.9", "Open Container Initiative", "Apache-2.0"),
            ("golang", "1.21.3", "Google LLC", "BSD-3-Clause"),
            ("libseccomp", "2.5.4", "Paul Moore", "LGPL-2.1"),
            ("iptables", "1.8.9", "Netfilter Core Team", "GPL-2.0"),
            ("openssl", "3.0.11", "OpenSSL Foundation", "Apache-2.0"),
            ("tini", "0.19.0", "Thomas Orozco", "MIT"),
            ("cli", "24.0.7", "Docker Inc", "Apache-2.0"),
            ("buildkit", "0.12.3", "Docker Inc", "Apache-2.0"),
        ],
    },
    {
        "name": "Kubernetes", "item_type": "application", "category": "Container Orchestration",
        "manufacturer": "Cloud Native Computing Foundation", "developer": "Google LLC", "version": "1.28.3",
        "description": "Open source container orchestration system",
        "components": [
            ("golang", "1.21.3", "Google LLC", "BSD-3-Clause"),
            ("etcd", "3.5.9", "CNCF", "Apache-2.0"),
            ("containerd", "1.7.8", "CNCF", "Apache-2.0"),
            ("coredns", "1.11.1", "CNCF", "Apache-2.0"),
            ("cni-plugins", "1.3.0", "CNCF", "Apache-2.0"),
            ("openssl", "3.0.11", "OpenSSL Foundation", "Apache-2.0"),
            ("grpc", "1.59.2", "Google LLC", "Apache-2.0"),
            ("protobuf", "3.21.12", "Google LLC", "BSD-3-Clause"),
            ("calico", "3.26.3", "Tigera", "Apache-2.0"),
            ("flannel", "0.22.3", "CoreOS", "Apache-2.0"),
        ],
    },
    {
        "name": "Podman", "item_type": "application", "category": "Container Runtime",
        "manufacturer": "Red Hat Inc", "developer": "Red Hat Inc", "version": "4.7.2",
        "description": "Daemonless container engine for OCI containers",
        "components": [
            ("golang", "1.21.3", "Google LLC", "BSD-3-Clause"),
            ("runc", "1.1.9", "Open Container Initiative", "Apache-2.0"),
            ("crun", "1.11.2", "Giuseppe Scrivano", "GPL-2.0"),
            ("conmon", "2.1.8", "Red Hat Inc", "Apache-2.0"),
            ("netavark", "1.8.0", "Red Hat Inc", "Apache-2.0"),
            ("aardvark-dns", "1.8.0", "Red Hat Inc", "Apache-2.0"),
            ("libseccomp", "2.5.4", "Paul Moore", "LGPL-2.1"),
        ],
    },
    # ── Web Frameworks ───────────────────────────────────────────────────────
    {
        "name": "Django", "item_type": "application", "category": "Web Framework",
        "manufacturer": "Django Software Foundation", "developer": "Django Software Foundation", "version": "4.2.7",
        "description": "High-level Python web framework that encourages rapid development",
        "components": [
            ("python", "3.11.6", "Python Software Foundation", "PSF-2.0"),
            ("sqlparse", "0.4.4", "Andi Albrecht", "BSD-3-Clause"),
            ("asgiref", "3.7.2", "Django Software Foundation", "BSD-3-Clause"),
            ("cryptography", "41.0.5", "Python Cryptographic Authority", "Apache-2.0"),
            ("psycopg2", "2.9.9", "Federico Di Gregorio", "LGPL-3.0"),
            ("pillow", "10.1.0", "Alex Clark", "HPND"),
            ("pytz", "2023.3", "Stuart Bishop", "MIT"),
            ("whitenoise", "6.6.0", "David Evans", "MIT"),
        ],
    },
    {
        "name": "FastAPI", "item_type": "application", "category": "Web Framework",
        "manufacturer": "Sebastián Ramírez", "developer": "Sebastián Ramírez", "version": "0.104.1",
        "description": "Modern, fast web framework for building APIs with Python",
        "components": [
            ("starlette", "0.27.0", "Encode", "BSD-3-Clause"),
            ("pydantic", "2.4.2", "Samuel Colvin", "MIT"),
            ("uvicorn", "0.24.0", "Encode", "BSD-3-Clause"),
            ("httpx", "0.25.1", "Encode", "BSD-3-Clause"),
            ("python-multipart", "0.0.6", "Andrew Dunstan", "Apache-2.0"),
            ("orjson", "3.9.10", "ijl", "Apache-2.0"),
            ("anyio", "3.7.1", "Alex Grönholm", "MIT"),
            ("click", "8.1.7", "Armin Ronacher", "BSD-3-Clause"),
        ],
    },
    {
        "name": "Flask", "item_type": "application", "category": "Web Framework",
        "manufacturer": "Pallets Projects", "developer": "Armin Ronacher", "version": "3.0.0",
        "description": "Lightweight WSGI web application framework in Python",
        "components": [
            ("werkzeug", "3.0.1", "Pallets Projects", "BSD-3-Clause"),
            ("jinja2", "3.1.2", "Pallets Projects", "BSD-3-Clause"),
            ("click", "8.1.7", "Armin Ronacher", "BSD-3-Clause"),
            ("itsdangerous", "2.1.2", "Pallets Projects", "BSD-3-Clause"),
            ("markupsafe", "2.1.3", "Pallets Projects", "BSD-3-Clause"),
            ("blinker", "1.6.3", "Jason Kirtland", "MIT"),
        ],
    },
    {
        "name": "Spring Boot", "item_type": "application", "category": "Java Framework",
        "manufacturer": "VMware Inc", "developer": "Pivotal Software", "version": "3.2.0",
        "description": "Java framework for building production-ready microservices",
        "components": [
            ("java", "17.0.9", "Eclipse Adoptium", "GPL-2.0"),
            ("spring-framework", "6.1.1", "VMware Inc", "Apache-2.0"),
            ("spring-security", "6.2.0", "VMware Inc", "Apache-2.0"),
            ("hibernate", "6.4.0", "Red Hat Inc", "LGPL-2.1"),
            ("jackson", "2.15.3", "FasterXML", "Apache-2.0"),
            ("tomcat", "10.1.16", "Apache Software Foundation", "Apache-2.0"),
            ("slf4j", "2.0.9", "QOS.ch", "MIT"),
            ("logback", "1.4.14", "QOS.ch", "LGPL-2.1"),
            ("micrometer", "1.12.0", "VMware Inc", "Apache-2.0"),
            ("hibernate-validator", "8.0.1", "Red Hat Inc", "Apache-2.0"),
        ],
    },
    {
        "name": "Express.js", "item_type": "application", "category": "Web Framework",
        "manufacturer": "OpenJS Foundation", "developer": "TJ Holowaychuk", "version": "4.18.2",
        "description": "Fast, unopinionated, minimalist web framework for Node.js",
        "components": [
            ("accepts", "1.3.8", "Jonathan Ong", "MIT"),
            ("body-parser", "1.20.2", "Douglas Wilson", "MIT"),
            ("cookie", "0.5.0", "Roman Shtylman", "MIT"),
            ("debug", "2.6.9", "Nathan Rajlich", "MIT"),
            ("depd", "2.0.0", "Douglas Wilson", "MIT"),
            ("encodeurl", "1.0.2", "Douglas Christopher Wilson", "MIT"),
            ("finalhandler", "1.2.0", "Douglas Wilson", "MIT"),
            ("fresh", "0.5.2", "TJ Holowaychuk", "MIT"),
            ("methods", "1.1.2", "JavaScript Standards", "MIT"),
            ("path-to-regexp", "0.1.7", "Blake Embrey", "MIT"),
            ("qs", "6.11.0", "TJ Holowaychuk", "BSD-3-Clause"),
            ("range-parser", "1.2.1", "TJ Holowaychuk", "MIT"),
            ("serve-static", "1.15.0", "Douglas Wilson", "MIT"),
        ],
    },
    {
        "name": "Laravel", "item_type": "application", "category": "Web Framework",
        "manufacturer": "Laravel LLC", "developer": "Taylor Otwell", "version": "10.35.0",
        "description": "PHP web application framework with expressive syntax",
        "components": [
            ("php", "8.2.12", "PHP Group", "PHP-3.01"),
            ("symfony", "6.3.8", "Symfony SAS", "MIT"),
            ("composer", "2.6.5", "Nils Adermann", "MIT"),
            ("carbon", "2.72.0", "Brian Nesbitt", "MIT"),
            ("monolog", "3.5.0", "Jordi Boggiano", "MIT"),
            ("doctrine-inflector", "2.0.8", "Doctrine Project", "MIT"),
            ("ramsey-uuid", "4.7.4", "Ben Ramsey", "MIT"),
            ("vlucas-phpdotenv", "5.6.0", "Vance Lucas", "BSD-3-Clause"),
            ("league-flysystem", "3.18.0", "Frank de Jonge", "MIT"),
        ],
    },
    {
        "name": "Ruby on Rails", "item_type": "application", "category": "Web Framework",
        "manufacturer": "Rails Core Team", "developer": "David Heinemeier Hansson", "version": "7.1.2",
        "description": "Server-side MVC web application framework written in Ruby",
        "components": [
            ("ruby", "3.2.2", "Yukihiro Matsumoto", "Ruby"),
            ("activerecord", "7.1.2", "Rails Core Team", "MIT"),
            ("actionpack", "7.1.2", "Rails Core Team", "MIT"),
            ("activesupport", "7.1.2", "Rails Core Team", "MIT"),
            ("rack", "3.0.8", "Leah Neukirchen", "MIT"),
            ("bundler", "2.4.22", "Bundler Team", "MIT"),
            ("puma", "6.4.0", "Evan Phoenix", "BSD-3-Clause"),
            ("nokogiri", "1.16.0", "Mike Dalessio", "MIT"),
            ("pg", "1.5.4", "Matz", "BSD-2-Clause"),
        ],
    },
    # ── Frontend Frameworks ──────────────────────────────────────────────────
    {
        "name": "React", "item_type": "application", "category": "Frontend Framework",
        "manufacturer": "Meta Platforms Inc", "developer": "Meta Platforms Inc", "version": "18.2.0",
        "description": "JavaScript library for building user interfaces",
        "components": [
            ("loose-envify", "1.4.0", "Andres Suarez", "MIT"),
            ("scheduler", "0.23.0", "Meta Platforms Inc", "MIT"),
            ("react-dom", "18.2.0", "Meta Platforms Inc", "MIT"),
            ("prop-types", "15.8.1", "Meta Platforms Inc", "MIT"),
            ("js-tokens", "4.0.0", "Simon Lydell", "MIT"),
        ],
    },
    {
        "name": "Vue.js", "item_type": "application", "category": "Frontend Framework",
        "manufacturer": "Evan You", "developer": "Evan You", "version": "3.3.8",
        "description": "Progressive JavaScript framework for building user interfaces",
        "components": [
            ("@vue/compiler-core", "3.3.8", "Evan You", "MIT"),
            ("@vue/compiler-dom", "3.3.8", "Evan You", "MIT"),
            ("@vue/reactivity", "3.3.8", "Evan You", "MIT"),
            ("@vue/runtime-core", "3.3.8", "Evan You", "MIT"),
            ("@vue/runtime-dom", "3.3.8", "Evan You", "MIT"),
            ("@vue/shared", "3.3.8", "Evan You", "MIT"),
        ],
    },
    {
        "name": "Angular", "item_type": "application", "category": "Frontend Framework",
        "manufacturer": "Google LLC", "developer": "Google LLC", "version": "17.0.3",
        "description": "Platform for building mobile and desktop web applications",
        "components": [
            ("typescript", "5.2.2", "Microsoft Corporation", "Apache-2.0"),
            ("rxjs", "7.8.1", "Ben Lesh", "Apache-2.0"),
            ("zone.js", "0.14.2", "Google LLC", "MIT"),
            ("tslib", "2.6.2", "Microsoft Corporation", "BSD-Zero"),
            ("@angular/cdk", "17.0.3", "Google LLC", "MIT"),
            ("@angular/material", "17.0.3", "Google LLC", "MIT"),
        ],
    },
    {
        "name": "Next.js", "item_type": "application", "category": "Frontend Framework",
        "manufacturer": "Vercel Inc", "developer": "Guillermo Rauch", "version": "14.0.3",
        "description": "React framework for production with SSR and static generation",
        "components": [
            ("react", "18.2.0", "Meta Platforms Inc", "MIT"),
            ("webpack", "5.89.0", "JS Foundation", "MIT"),
            ("typescript", "5.2.2", "Microsoft Corporation", "Apache-2.0"),
            ("postcss", "8.4.31", "Andrey Sitnik", "MIT"),
            ("styled-jsx", "5.1.1", "Vercel Inc", "MIT"),
            ("@next/swc-linux-x64-gnu", "14.0.3", "Vercel Inc", "MIT"),
            ("browserslist", "4.22.1", "Andrey Sitnik", "MIT"),
        ],
    },
    {
        "name": "Svelte", "item_type": "application", "category": "Frontend Framework",
        "manufacturer": "Svelte Team", "developer": "Rich Harris", "version": "4.2.7",
        "description": "Cybernetically enhanced web apps compiler",
        "components": [
            ("acorn", "8.11.2", "Marijn Haverbeke", "MIT"),
            ("magic-string", "0.30.5", "Rich Harris", "MIT"),
            ("periscopic", "3.1.0", "Rich Harris", "MIT"),
            ("aria-query", "5.3.0", "A11yance", "Apache-2.0"),
            ("axobject-query", "4.0.0", "A11yance", "Apache-2.0"),
        ],
    },
    # ── Runtimes & Languages ─────────────────────────────────────────────────
    {
        "name": "Node.js", "item_type": "application", "category": "JavaScript Runtime",
        "manufacturer": "OpenJS Foundation", "developer": "Ryan Dahl", "version": "20.10.0",
        "description": "JavaScript runtime built on Chrome's V8 engine",
        "components": [
            ("v8", "11.8.172", "Google LLC", "BSD-3-Clause"),
            ("libuv", "1.47.0", "libuv contributors", "MIT"),
            ("openssl", "3.0.11", "OpenSSL Foundation", "Apache-2.0"),
            ("zlib", "1.3.1", "Jean-loup Gailly", "Zlib"),
            ("c-ares", "1.22.1", "Daniel Stenberg", "MIT"),
            ("llhttp", "9.1.3", "Fedor Indutny", "MIT"),
            ("nghttp2", "1.58.0", "Tatsuhiro Tsujikawa", "MIT"),
            ("npm", "10.2.4", "npm Inc", "Artistic-2.0"),
            ("uvwasi", "0.0.19", "Node.js contributors", "MIT"),
        ],
    },
    {
        "name": "Python", "item_type": "application", "category": "Programming Language Runtime",
        "manufacturer": "Python Software Foundation", "developer": "Guido van Rossum", "version": "3.12.0",
        "description": "High-level general-purpose programming language",
        "components": [
            ("openssl", "3.0.11", "OpenSSL Foundation", "Apache-2.0"),
            ("zlib", "1.3.1", "Jean-loup Gailly", "Zlib"),
            ("libffi", "3.4.4", "Anthony Green", "MIT"),
            ("readline", "8.2", "Free Software Foundation", "GPL-3.0"),
            ("sqlite", "3.43.2", "D. Richard Hipp", "blessing"),
            ("expat", "2.5.0", "Expat Project", "MIT"),
            ("bzip2", "1.0.8", "Julian Seward", "bzip2-1.0.6"),
            ("xz", "5.4.5", "Tukaani Project", "0BSD"),
            ("gdbm", "1.23", "Free Software Foundation", "GPL-3.0"),
        ],
    },
    {
        "name": "Go", "item_type": "application", "category": "Programming Language Runtime",
        "manufacturer": "Google LLC", "developer": "Robert Griesemer", "version": "1.21.4",
        "description": "Open source programming language for reliable, efficient software",
        "components": [
            ("golang.org/x/sys", "0.14.0", "Google LLC", "BSD-3-Clause"),
            ("golang.org/x/net", "0.17.0", "Google LLC", "BSD-3-Clause"),
            ("golang.org/x/text", "0.13.0", "Google LLC", "BSD-3-Clause"),
            ("golang.org/x/crypto", "0.14.0", "Google LLC", "BSD-3-Clause"),
            ("golang.org/x/tools", "0.14.0", "Google LLC", "BSD-3-Clause"),
        ],
    },
    # ── Security ─────────────────────────────────────────────────────────────
    {
        "name": "OpenSSL", "item_type": "application", "category": "Security Library",
        "manufacturer": "OpenSSL Foundation", "developer": "OpenSSL Project", "version": "3.0.11",
        "description": "Toolkit for TLS and general-purpose cryptography",
        "components": [
            ("perl", "5.38.0", "Larry Wall", "Artistic-1.0-Perl"),
            ("zlib", "1.3.1", "Jean-loup Gailly", "Zlib"),
            ("glibc", "2.38", "GNU Project", "LGPL-2.1"),
        ],
    },
    {
        "name": "OpenSSH", "item_type": "application", "category": "Security",
        "manufacturer": "OpenBSD Project", "developer": "OpenBSD Project", "version": "9.5",
        "description": "Secure Shell protocol suite for encrypted connections",
        "components": [
            ("openssl", "3.0.11", "OpenSSL Foundation", "Apache-2.0"),
            ("zlib", "1.3.1", "Jean-loup Gailly", "Zlib"),
            ("libcrypto", "3.0.11", "OpenSSL Foundation", "Apache-2.0"),
            ("pam", "1.5.3", "Linux-PAM Project", "GPL-2.0"),
            ("glibc", "2.38", "GNU Project", "LGPL-2.1"),
            ("libedit", "3.1", "NetBSD Project", "BSD-3-Clause"),
            ("krb5", "1.21.2", "MIT Kerberos Team", "MIT"),
        ],
    },
    {
        "name": "Vault", "item_type": "application", "category": "Secrets Management",
        "manufacturer": "HashiCorp", "developer": "HashiCorp", "version": "1.15.2",
        "description": "Tool for secrets management, encryption, and privileged access",
        "components": [
            ("golang", "1.21.3", "Google LLC", "BSD-3-Clause"),
            ("openssl", "3.0.11", "OpenSSL Foundation", "Apache-2.0"),
            ("consul", "1.16.3", "HashiCorp", "BUSL-1.1"),
            ("grpc", "1.59.2", "Google LLC", "Apache-2.0"),
            ("bolt", "1.3.1", "Ben Johnson", "MIT"),
            ("jwt-go", "3.2.0", "Dave Grijalva", "MIT"),
            ("aws-sdk-go", "1.47.9", "Amazon Web Services", "Apache-2.0"),
        ],
    },
    {
        "name": "Snort IDS", "item_type": "application", "category": "Intrusion Detection",
        "manufacturer": "Cisco Systems", "developer": "Martin Roesch", "version": "3.1.64.0",
        "description": "Open source network intrusion detection and prevention system",
        "components": [
            ("libpcap", "1.10.4", "TCPDUMP Group", "BSD-3-Clause"),
            ("pcre2", "10.42", "PCRE2 Project", "BSD-2-Clause"),
            ("openssl", "3.0.11", "OpenSSL Foundation", "Apache-2.0"),
            ("daq", "3.0.13", "Cisco Systems", "GPL-2.0"),
            ("hyperscan", "5.4.2", "Intel Corporation", "BSD-3-Clause"),
            ("luajit", "2.1.0", "Mike Pall", "MIT"),
            ("libdnet", "1.14", "Dug Song", "BSD-3-Clause"),
            ("flatbuffers", "23.5.26", "Google LLC", "Apache-2.0"),
        ],
    },
    {
        "name": "Wireshark", "item_type": "application", "category": "Network Analysis",
        "manufacturer": "Wireshark Foundation", "developer": "Gerald Combs", "version": "4.2.0",
        "description": "World's foremost network protocol analyzer",
        "components": [
            ("pcap", "1.10.4", "TCPDUMP Group", "BSD-3-Clause"),
            ("glib2", "2.78.1", "GNOME Project", "LGPL-2.1"),
            ("qt6", "6.6.0", "The Qt Company", "LGPL-3.0"),
            ("openssl", "3.0.11", "OpenSSL Foundation", "Apache-2.0"),
            ("zlib", "1.3.1", "Jean-loup Gailly", "Zlib"),
            ("libxml2", "2.11.5", "GNOME Project", "MIT"),
            ("c-ares", "1.22.1", "Daniel Stenberg", "MIT"),
            ("libgcrypt", "1.10.3", "Werner Koch", "LGPL-2.1"),
            ("lua", "5.4.6", "PUC-Rio", "MIT"),
        ],
    },
    # ── Monitoring & Observability ───────────────────────────────────────────
    {
        "name": "Prometheus", "item_type": "application", "category": "Monitoring",
        "manufacturer": "Cloud Native Computing Foundation", "developer": "Prometheus Authors", "version": "2.47.2",
        "description": "Systems monitoring and alerting toolkit",
        "components": [
            ("golang", "1.21.3", "Google LLC", "BSD-3-Clause"),
            ("leveldb", "1.31.0", "Google LLC", "BSD-3-Clause"),
            ("snappy", "1.1.10", "Google LLC", "BSD-3-Clause"),
            ("grpc", "1.59.2", "Google LLC", "Apache-2.0"),
            ("protobuf", "3.21.12", "Google LLC", "BSD-3-Clause"),
            ("opentelemetry", "1.21.0", "CNCF", "Apache-2.0"),
        ],
    },
    {
        "name": "Grafana", "item_type": "application", "category": "Observability",
        "manufacturer": "Grafana Labs", "developer": "Grafana Labs", "version": "10.2.2",
        "description": "Open source analytics and monitoring platform",
        "components": [
            ("golang", "1.21.3", "Google LLC", "BSD-3-Clause"),
            ("react", "18.2.0", "Meta Platforms Inc", "MIT"),
            ("d3", "7.8.5", "Observable Inc", "ISC"),
            ("grafana-ui", "10.2.2", "Grafana Labs", "Apache-2.0"),
            ("prometheus-client", "1.17.0", "Prometheus Authors", "Apache-2.0"),
            ("opentelemetry", "1.21.0", "CNCF", "Apache-2.0"),
            ("sqlite", "3.43.2", "D. Richard Hipp", "blessing"),
            ("grpc", "1.59.2", "Google LLC", "Apache-2.0"),
        ],
    },
    {
        "name": "Datadog Agent", "item_type": "application", "category": "Monitoring",
        "manufacturer": "Datadog Inc", "developer": "Datadog Inc", "version": "7.48.1",
        "description": "Monitoring agent for collecting metrics and events",
        "components": [
            ("golang", "1.21.3", "Google LLC", "BSD-3-Clause"),
            ("openssl", "3.0.11", "OpenSSL Foundation", "Apache-2.0"),
            ("python", "3.11.6", "Python Software Foundation", "PSF-2.0"),
            ("protobuf", "3.21.12", "Google LLC", "BSD-3-Clause"),
            ("grpc", "1.59.2", "Google LLC", "Apache-2.0"),
            ("docker", "24.0.7", "Docker Inc", "Apache-2.0"),
        ],
    },
    # ── Message Brokers ──────────────────────────────────────────────────────
    {
        "name": "Apache Kafka", "item_type": "application", "category": "Message Broker",
        "manufacturer": "Apache Software Foundation", "developer": "LinkedIn Corporation", "version": "3.6.0",
        "description": "Distributed event streaming platform for high-performance pipelines",
        "components": [
            ("java", "17.0.9", "Eclipse Adoptium", "GPL-2.0"),
            ("scala", "2.13.12", "EPFL", "Apache-2.0"),
            ("zookeeper", "3.8.3", "Apache Software Foundation", "Apache-2.0"),
            ("snappy", "1.1.10", "Google LLC", "BSD-3-Clause"),
            ("lz4", "1.9.4", "Yann Collet", "BSD-2-Clause"),
            ("jackson", "2.15.3", "FasterXML", "Apache-2.0"),
            ("slf4j", "2.0.9", "QOS.ch", "MIT"),
            ("log4j2", "2.21.1", "Apache Software Foundation", "Apache-2.0"),
        ],
    },
    {
        "name": "RabbitMQ", "item_type": "application", "category": "Message Broker",
        "manufacturer": "Broadcom Inc", "developer": "Pivotal Software", "version": "3.12.8",
        "description": "Open source message broker implementing AMQP protocol",
        "components": [
            ("erlang", "26.1.2", "Ericsson AB", "Apache-2.0"),
            ("openssl", "3.0.11", "OpenSSL Foundation", "Apache-2.0"),
            ("lager", "3.9.2", "Basho Technologies", "Apache-2.0"),
            ("cowboy", "2.10.0", "Loïc Hoguin", "ISC"),
            ("ranch", "2.1.0", "Loïc Hoguin", "ISC"),
        ],
    },
    # ── DevOps Tools ─────────────────────────────────────────────────────────
    {
        "name": "Jenkins", "item_type": "application", "category": "CI/CD",
        "manufacturer": "Jenkins Project", "developer": "Kohsuke Kawaguchi", "version": "2.432",
        "description": "Open source automation server for CI/CD pipelines",
        "components": [
            ("java", "17.0.9", "Eclipse Adoptium", "GPL-2.0"),
            ("spring-framework", "5.3.30", "VMware Inc", "Apache-2.0"),
            ("stapler", "1887.v149994e1e8e7", "Jenkins Project", "BSD-2-Clause"),
            ("guava", "32.1.3", "Google LLC", "Apache-2.0"),
            ("jackson", "2.15.3", "FasterXML", "Apache-2.0"),
            ("groovy", "3.0.19", "Apache Software Foundation", "Apache-2.0"),
            ("ant", "1.10.14", "Apache Software Foundation", "Apache-2.0"),
            ("jetty", "10.0.18", "Eclipse Foundation", "Apache-2.0"),
        ],
    },
    {
        "name": "GitLab CE", "item_type": "application", "category": "DevOps Platform",
        "manufacturer": "GitLab Inc", "developer": "GitLab Inc", "version": "16.6.0",
        "description": "Complete DevOps platform delivered as a single application",
        "components": [
            ("ruby", "3.1.4", "Yukihiro Matsumoto", "Ruby"),
            ("rails", "7.0.8", "David Heinemeier Hansson", "MIT"),
            ("postgresql", "14.10", "PostgreSQL Global Development Group", "PostgreSQL"),
            ("redis", "7.2.3", "Redis Ltd", "RSALv2"),
            ("nginx", "1.25.3", "F5 Inc", "BSD-2-Clause"),
            ("gitaly", "16.6.0", "GitLab Inc", "MIT"),
            ("prometheus", "2.47.2", "Prometheus Authors", "Apache-2.0"),
            ("go", "1.21.3", "Google LLC", "BSD-3-Clause"),
            ("yarn", "1.22.21", "Meta Platforms Inc", "BSD-2-Clause"),
            ("webpack", "5.89.0", "JS Foundation", "MIT"),
        ],
    },
    {
        "name": "Terraform", "item_type": "application", "category": "Infrastructure as Code",
        "manufacturer": "HashiCorp", "developer": "HashiCorp", "version": "1.6.4",
        "description": "Infrastructure as code tool for cloud resource provisioning",
        "components": [
            ("golang", "1.21.3", "Google LLC", "BSD-3-Clause"),
            ("grpc", "1.59.2", "Google LLC", "Apache-2.0"),
            ("aws-sdk-go", "1.47.9", "Amazon Web Services", "Apache-2.0"),
            ("google-cloud-go", "0.110.9", "Google LLC", "Apache-2.0"),
            ("azure-sdk-for-go", "68.0.0", "Microsoft Corporation", "MIT"),
            ("hashicorp-hcl", "2.19.1", "HashiCorp", "MPL-2.0"),
            ("zclconf-go-cty", "1.14.1", "Martin Atkins", "MIT"),
        ],
    },
    {
        "name": "Ansible", "item_type": "application", "category": "Configuration Management",
        "manufacturer": "Red Hat Inc", "developer": "Michael DeHaan", "version": "8.6.1",
        "description": "IT automation tool for configuration management and deployment",
        "components": [
            ("python", "3.11.6", "Python Software Foundation", "PSF-2.0"),
            ("cryptography", "41.0.5", "Python Cryptographic Authority", "Apache-2.0"),
            ("jinja2", "3.1.2", "Pallets Projects", "BSD-3-Clause"),
            ("pyyaml", "6.0.1", "Kirill Simonov", "MIT"),
            ("paramiko", "3.3.1", "Jeff Forcier", "LGPL-2.1"),
            ("cffi", "1.16.0", "Armin Rigo", "MIT"),
            ("resolvelib", "1.0.1", "Tzu-ping Chung", "ISC"),
        ],
    },
    # ── CMS & Applications ───────────────────────────────────────────────────
    {
        "name": "WordPress", "item_type": "application", "category": "Content Management System",
        "manufacturer": "Automattic Inc", "developer": "WordPress Foundation", "version": "6.4.1",
        "description": "World's most popular CMS powering 43% of all websites",
        "components": [
            ("php", "8.2.12", "PHP Group", "PHP-3.01"),
            ("mysql", "8.2.0", "Oracle Corporation", "GPL-2.0"),
            ("jquery", "3.7.1", "OpenJS Foundation", "MIT"),
            ("backbone.js", "1.4.1", "Jeremy Ashkenas", "MIT"),
            ("underscore.js", "1.13.6", "Jeremy Ashkenas", "MIT"),
            ("sodium-compat", "1.20.0", "Paragon Initiative", "ISC"),
            ("phpmailer", "6.8.1", "Marcus Bointon", "LGPL-2.1"),
            ("simplepie", "1.8.0", "SimplePie Team", "BSD-3-Clause"),
        ],
    },
    # ── ML & Data ────────────────────────────────────────────────────────────
    {
        "name": "TensorFlow", "item_type": "application", "category": "Machine Learning",
        "manufacturer": "Google LLC", "developer": "Google Brain Team", "version": "2.14.0",
        "description": "Open source machine learning framework for research and production",
        "components": [
            ("python", "3.11.6", "Python Software Foundation", "PSF-2.0"),
            ("numpy", "1.26.1", "NumPy Community", "BSD-3-Clause"),
            ("protobuf", "4.24.4", "Google LLC", "BSD-3-Clause"),
            ("grpc", "1.59.2", "Google LLC", "Apache-2.0"),
            ("absl-py", "2.0.0", "Google LLC", "Apache-2.0"),
            ("keras", "2.14.0", "Google LLC", "Apache-2.0"),
            ("flatbuffers", "23.5.26", "Google LLC", "Apache-2.0"),
            ("eigen", "3.4.0", "Eigen Community", "MPL-2.0"),
        ],
    },
    {
        "name": "PyTorch", "item_type": "application", "category": "Machine Learning",
        "manufacturer": "Meta Platforms Inc", "developer": "Meta AI Research", "version": "2.1.1",
        "description": "Open source machine learning framework with dynamic computation graphs",
        "components": [
            ("python", "3.11.6", "Python Software Foundation", "PSF-2.0"),
            ("numpy", "1.26.1", "NumPy Community", "BSD-3-Clause"),
            ("pybind11", "2.11.1", "Wenzel Jakob", "BSD-2-Clause"),
            ("eigen", "3.4.0", "Eigen Community", "MPL-2.0"),
            ("sleef", "3.5.1", "Naoki Shibata", "BSL-1.0"),
            ("fmt", "9.1.0", "Victor Zverovich", "MIT"),
            ("foxi", "0.0.1", "Meta Platforms Inc", "MIT"),
            ("onnx", "1.14.1", "ONNX Community", "Apache-2.0"),
        ],
    },
    # ── Devices ──────────────────────────────────────────────────────────────
    {
        "name": "Raspberry Pi OS", "item_type": "device", "category": "Single Board Computer OS",
        "manufacturer": "Raspberry Pi Foundation", "developer": "Raspberry Pi Foundation", "version": "12 Bookworm",
        "description": "Official OS for Raspberry Pi single-board computers based on Debian",
        "components": [
            ("linux-kernel", "6.1.61", "Linux Foundation", "GPL-2.0"),
            ("u-boot", "2023.10", "DENX Software Engineering", "GPL-2.0"),
            ("busybox", "1.36.1", "Bruce Perens", "GPL-2.0"),
            ("openssl", "3.0.11", "OpenSSL Foundation", "Apache-2.0"),
            ("systemd", "254", "systemd Project", "LGPL-2.1"),
            ("glibc", "2.38", "GNU Project", "LGPL-2.1"),
            ("python3", "3.11.6", "Python Software Foundation", "PSF-2.0"),
            ("apt", "2.7.3", "Debian Project", "GPL-2.0"),
            ("bash", "5.2.15", "Free Software Foundation", "GPL-3.0"),
            ("curl", "8.4.0", "Daniel Stenberg", "curl"),
            ("openssh", "9.5", "OpenBSD Project", "BSD-2-Clause"),
            ("dpkg", "1.22.1", "Debian Project", "GPL-2.0"),
        ],
    },
    {
        "name": "Arduino Firmware", "item_type": "device", "category": "Microcontroller Platform",
        "manufacturer": "Arduino LLC", "developer": "Arduino LLC", "version": "1.8.6",
        "description": "Firmware and toolchain for Arduino microcontroller boards",
        "components": [
            ("avr-libc", "2.1.0", "AVR-LibC Team", "BSD-3-Clause"),
            ("avr-gcc", "7.3.0", "Free Software Foundation", "GPL-3.0"),
            ("arduino-core", "1.8.6", "Arduino LLC", "LGPL-2.1"),
            ("wire-library", "1.0", "Arduino LLC", "LGPL-2.1"),
            ("spi-library", "1.0", "Arduino LLC", "LGPL-2.1"),
            ("sd-library", "1.2.4", "Arduino LLC", "LGPL-2.1"),
            ("ethernet-library", "2.0.0", "Arduino LLC", "LGPL-2.1"),
        ],
    },
    {
        "name": "OpenWrt", "item_type": "device", "category": "Router Firmware",
        "manufacturer": "OpenWrt Project", "developer": "OpenWrt Community", "version": "23.05.1",
        "description": "Linux-based firmware for embedded devices especially routers",
        "components": [
            ("linux-kernel", "5.15.137", "Linux Foundation", "GPL-2.0"),
            ("busybox", "1.36.1", "Bruce Perens", "GPL-2.0"),
            ("openssl", "3.0.11", "OpenSSL Foundation", "Apache-2.0"),
            ("opkg", "2022-02-24", "OpenWrt Project", "GPL-2.0"),
            ("dnsmasq", "2.89", "Simon Kelley", "GPL-2.0"),
            ("dropbear", "2022.83", "Matt Johnston", "MIT"),
            ("iptables", "1.8.9", "Netfilter Core Team", "GPL-2.0"),
            ("uci", "2023-01-30", "OpenWrt Project", "LGPL-2.1"),
            ("luci", "23.05", "OpenWrt Project", "Apache-2.0"),
            ("ppp", "2.4.9", "Paul Mackerras", "BSD-3-Clause"),
            ("wpad", "2023-09-01", "Jouni Malinen", "BSD-3-Clause"),
        ],
    },
    {
        "name": "Android AOSP", "item_type": "device", "category": "Mobile Operating System",
        "manufacturer": "Google LLC", "developer": "Google LLC", "version": "14.0",
        "description": "Android Open Source Project base mobile operating system",
        "components": [
            ("linux-kernel", "6.1.25", "Linux Foundation", "GPL-2.0"),
            ("bionic-libc", "14.0", "Google LLC", "BSD-2-Clause"),
            ("art-runtime", "14.0", "Google LLC", "Apache-2.0"),
            ("openssl", "3.0.11", "OpenSSL Foundation", "Apache-2.0"),
            ("boringssl", "14.0", "Google LLC", "OpenSSL"),
            ("sqlite", "3.43.2", "D. Richard Hipp", "blessing"),
            ("zlib", "1.3", "Jean-loup Gailly", "Zlib"),
            ("v8-engine", "11.8", "Google LLC", "BSD-3-Clause"),
            ("freetype", "2.13.2", "FreeType Project", "FTL"),
            ("harfbuzz", "8.2.2", "HarfBuzz Team", "MIT"),
        ],
    },
    {
        "name": "Ubuntu Server", "item_type": "device", "category": "Server Operating System",
        "manufacturer": "Canonical Ltd", "developer": "Canonical Ltd", "version": "22.04.3 LTS",
        "description": "Enterprise-grade Linux server operating system with long-term support",
        "components": [
            ("linux-kernel", "5.15.0", "Linux Foundation", "GPL-2.0"),
            ("systemd", "249.11", "systemd Project", "LGPL-2.1"),
            ("glibc", "2.35", "GNU Project", "LGPL-2.1"),
            ("openssl", "3.0.2", "OpenSSL Foundation", "Apache-2.0"),
            ("apt", "2.4.10", "Debian Project", "GPL-2.0"),
            ("bash", "5.1.16", "Free Software Foundation", "GPL-3.0"),
            ("python3", "3.10.12", "Python Software Foundation", "PSF-2.0"),
            ("openssh", "8.9", "OpenBSD Project", "BSD-2-Clause"),
            ("curl", "7.81.0", "Daniel Stenberg", "curl"),
            ("snap", "2.60.4", "Canonical Ltd", "GPL-3.0"),
            ("grub2", "2.06", "GNU Project", "GPL-3.0"),
            ("lvm2", "2.03.11", "Red Hat Inc", "GPL-2.0"),
        ],
    },
    {
        "name": "Cisco IOS Router", "item_type": "device", "category": "Network Device",
        "manufacturer": "Cisco Systems", "developer": "Cisco Systems", "version": "15.9.3M6",
        "description": "Enterprise router running Cisco IOS operating system",
        "components": [
            ("cisco-ios", "15.9.3M6", "Cisco Systems", "Cisco-proprietary"),
            ("openssl", "1.0.2u", "OpenSSL Foundation", "OpenSSL"),
            ("busybox", "1.29.3", "Bruce Perens", "GPL-2.0"),
            ("linux-kernel", "4.14.304", "Linux Foundation", "GPL-2.0"),
            ("openssh", "7.4p1", "OpenBSD Project", "BSD-2-Clause"),
            ("snmp", "5.7.3", "SNMP Project", "BSD-3-Clause"),
            ("curl", "7.82.0", "Daniel Stenberg", "curl"),
            ("tcpdump", "4.99.1", "TCPDUMP Group", "BSD-3-Clause"),
            ("python", "2.7.18", "Python Software Foundation", "PSF-2.0"),
            ("lua", "5.3.6", "PUC-Rio", "MIT"),
        ],
    },
    {
        "name": "pfSense", "item_type": "device", "category": "Firewall",
        "manufacturer": "Netgate", "developer": "Netgate", "version": "2.7.2",
        "description": "Open source firewall and router software distribution based on FreeBSD",
        "components": [
            ("freebsd", "14.0", "FreeBSD Foundation", "BSD-2-Clause"),
            ("openssl", "3.0.11", "OpenSSL Foundation", "Apache-2.0"),
            ("strongswan", "5.9.12", "strongSwan Project", "GPL-2.0"),
            ("openvpn", "2.6.8", "OpenVPN Inc", "GPL-2.0"),
            ("php", "8.2.12", "PHP Group", "PHP-3.01"),
            ("lighttpd", "1.4.72", "Jan Kneschke", "BSD-3-Clause"),
            ("squid", "6.5", "Squid Project", "GPL-2.0"),
            ("snort", "3.1.64.0", "Cisco Systems", "GPL-2.0"),
            ("unbound", "1.19.0", "NLnet Labs", "BSD-3-Clause"),
            ("haproxy", "2.8.5", "HAProxy Technologies", "GPL-2.0"),
        ],
    },
    {
        "name": "VMware ESXi", "item_type": "device", "category": "Hypervisor",
        "manufacturer": "VMware Inc", "developer": "VMware Inc", "version": "8.0 Update 2",
        "description": "Enterprise-class bare-metal hypervisor for server virtualization",
        "components": [
            ("vmkernel", "8.0.2", "VMware Inc", "VMware-proprietary"),
            ("openssl", "3.0.8", "OpenSSL Foundation", "Apache-2.0"),
            ("busybox", "1.35.0", "Bruce Perens", "GPL-2.0"),
            ("python", "3.8.17", "Python Software Foundation", "PSF-2.0"),
            ("curl", "8.1.2", "Daniel Stenberg", "curl"),
            ("openssh", "9.3p1", "OpenBSD Project", "BSD-2-Clause"),
            ("glibc", "2.35", "GNU Project", "LGPL-2.1"),
            ("libxml2", "2.10.4", "GNOME Project", "MIT"),
            ("zlib", "1.2.13", "Jean-loup Gailly", "Zlib"),
            ("tcl", "8.6.13", "Regents of UCB", "TCL"),
        ],
    },
    {
        "name": "ESP32 Firmware", "item_type": "device", "category": "IoT Microcontroller",
        "manufacturer": "Espressif Systems", "developer": "Espressif Systems", "version": "5.1.2",
        "description": "Firmware for ESP32 series IoT microcontrollers with WiFi and Bluetooth",
        "components": [
            ("freertos", "10.5.1", "Amazon Web Services", "MIT"),
            ("lwip", "2.1.3", "Adam Dunkels", "BSD-3-Clause"),
            ("mbedtls", "3.4.0", "ARM Limited", "Apache-2.0"),
            ("esp-idf", "5.1.2", "Espressif Systems", "Apache-2.0"),
            ("newlib", "4.1.0", "Red Hat Inc", "BSD-3-Clause"),
            ("xtensa-lx-rt", "0.9.0", "Espressif Systems", "MIT"),
            ("bt-bluedroid", "5.1.2", "Espressif Systems", "Apache-2.0"),
        ],
    },
    {
        "name": "Raspberry Pi 4 Model B", "item_type": "device", "category": "Single Board Computer",
        "manufacturer": "Raspberry Pi Foundation", "developer": "Raspberry Pi Foundation", "version": "4B Rev 1.5",
        "description": "Popular single-board computer for education and IoT applications",
        "components": [
            ("linux-kernel", "6.1.61", "Linux Foundation", "GPL-2.0"),
            ("u-boot", "2023.10", "DENX Software Engineering", "GPL-2.0"),
            ("videocore-firmware", "1.20231030", "Raspberry Pi Foundation", "Raspberry-Pi-proprietary"),
            ("openssl", "3.0.11", "OpenSSL Foundation", "Apache-2.0"),
            ("systemd", "254", "systemd Project", "LGPL-2.1"),
            ("glibc", "2.38", "GNU Project", "LGPL-2.1"),
            ("mesa", "23.3.0", "Mesa Project", "MIT"),
            ("alsa-lib", "1.2.10", "ALSA Project", "LGPL-2.1"),
            ("bluez", "5.70", "Linux Bluetooth", "GPL-2.0"),
            ("wpa-supplicant", "2.10", "Jouni Malinen", "BSD-3-Clause"),
        ],
    },
    # ── Additional Applications ──────────────────────────────────────────────
    {
        "name": "curl", "item_type": "application", "category": "Network Tool",
        "manufacturer": "Daniel Stenberg", "developer": "Daniel Stenberg", "version": "8.4.0",
        "description": "Command line tool and library for transferring data with URLs",
        "components": [
            ("openssl", "3.0.11", "OpenSSL Foundation", "Apache-2.0"),
            ("zlib", "1.3.1", "Jean-loup Gailly", "Zlib"),
            ("libssh2", "1.11.0", "Sara Golemon", "BSD-3-Clause"),
            ("nghttp2", "1.58.0", "Tatsuhiro Tsujikawa", "MIT"),
            ("c-ares", "1.22.1", "Daniel Stenberg", "MIT"),
            ("libidn2", "2.3.4", "Simon Josefsson", "LGPL-3.0"),
            ("libpsl", "0.21.2", "Tim Ruehsen", "MIT"),
        ],
    },
    {
        "name": "Git", "item_type": "application", "category": "Version Control",
        "manufacturer": "Git Project", "developer": "Linus Torvalds", "version": "2.42.1",
        "description": "Distributed version control system for tracking code changes",
        "components": [
            ("openssl", "3.0.11", "OpenSSL Foundation", "Apache-2.0"),
            ("zlib", "1.3.1", "Jean-loup Gailly", "Zlib"),
            ("libpcre2", "10.42", "PCRE2 Project", "BSD-2-Clause"),
            ("curl", "8.4.0", "Daniel Stenberg", "curl"),
            ("expat", "2.5.0", "Expat Project", "MIT"),
            ("gettext", "0.22.3", "Free Software Foundation", "GPL-3.0"),
            ("perl", "5.38.0", "Larry Wall", "Artistic-1.0-Perl"),
            ("python3", "3.11.6", "Python Software Foundation", "PSF-2.0"),
        ],
    },
    {
        "name": "Splunk Enterprise", "item_type": "application", "category": "SIEM",
        "manufacturer": "Splunk Inc", "developer": "Splunk Inc", "version": "9.1.2",
        "description": "Platform for searching, monitoring and analyzing machine-generated data",
        "components": [
            ("python", "3.7.17", "Python Software Foundation", "PSF-2.0"),
            ("openssl", "1.1.1w", "OpenSSL Foundation", "OpenSSL"),
            ("sqlite", "3.43.2", "D. Richard Hipp", "blessing"),
            ("curl", "8.4.0", "Daniel Stenberg", "curl"),
            ("libxml2", "2.9.14", "GNOME Project", "MIT"),
            ("zlib", "1.2.13", "Jean-loup Gailly", "Zlib"),
            ("apr", "1.7.4", "Apache Software Foundation", "Apache-2.0"),
            ("openldap", "2.6.6", "OpenLDAP Foundation", "OLDAP-2.8"),
        ],
    },
    {
        "name": "OpenVPN", "item_type": "application", "category": "VPN",
        "manufacturer": "OpenVPN Inc", "developer": "James Yonan", "version": "2.6.8",
        "description": "Open source VPN solution for secure network connections",
        "components": [
            ("openssl", "3.0.11", "OpenSSL Foundation", "Apache-2.0"),
            ("lzo", "2.10", "Markus Franz Xaver Oberhumer", "GPL-2.0"),
            ("libnl", "3.7.0", "Thomas Graf", "LGPL-2.1"),
            ("pam", "1.5.3", "Linux-PAM Project", "GPL-2.0"),
            ("libsystemd", "254", "systemd Project", "LGPL-2.1"),
            ("pkcs11-helper", "1.29.0", "Alon Bar-Lev", "BSD-3-Clause"),
        ],
    },
    {
        "name": "WireGuard", "item_type": "application", "category": "VPN",
        "manufacturer": "Jason A. Donenfeld", "developer": "Jason A. Donenfeld", "version": "1.0.20210914",
        "description": "Simple and fast VPN using modern cryptography principles",
        "components": [
            ("linux-kernel", "6.1.0", "Linux Foundation", "GPL-2.0"),
            ("libmnl", "1.0.5", "Pablo Neira Ayuso", "LGPL-2.1"),
            ("wireguard-tools", "1.0.20210914", "Jason A. Donenfeld", "GPL-2.0"),
        ],
    },
    {
        "name": "Nginx Proxy Manager", "item_type": "application", "category": "Reverse Proxy",
        "manufacturer": "Jamie Curnow", "developer": "Jamie Curnow", "version": "2.10.4",
        "description": "GUI for managing Nginx proxy hosts with SSL certificate management",
        "components": [
            ("nginx", "1.25.3", "F5 Inc", "BSD-2-Clause"),
            ("node.js", "18.18.2", "OpenJS Foundation", "MIT"),
            ("openssl", "3.0.11", "OpenSSL Foundation", "Apache-2.0"),
            ("certbot", "2.7.4", "Electronic Frontier Foundation", "Apache-2.0"),
            ("mysql", "8.2.0", "Oracle Corporation", "GPL-2.0"),
        ],
    },
    {
        "name": "Keycloak", "item_type": "application", "category": "Identity Management",
        "manufacturer": "Red Hat Inc", "developer": "Red Hat Inc", "version": "23.0.1",
        "description": "Open source Identity and Access Management solution",
        "components": [
            ("java", "17.0.9", "Eclipse Adoptium", "GPL-2.0"),
            ("wildfly", "30.0.1", "Red Hat Inc", "LGPL-2.1"),
            ("keycloak-core", "23.0.1", "Red Hat Inc", "Apache-2.0"),
            ("jackson", "2.15.3", "FasterXML", "Apache-2.0"),
            ("bouncycastle", "1.77", "Legion of the Bouncy Castle", "MIT"),
            ("hibernate", "6.4.0", "Red Hat Inc", "LGPL-2.1"),
            ("infinispan", "14.0.21", "Red Hat Inc", "Apache-2.0"),
        ],
    },
    {
        "name": "MinIO", "item_type": "application", "category": "Object Storage",
        "manufacturer": "MinIO Inc", "developer": "MinIO Inc", "version": "RELEASE.2023-11-15T20-43-25Z",
        "description": "High-performance S3-compatible object storage",
        "components": [
            ("golang", "1.21.3", "Google LLC", "BSD-3-Clause"),
            ("openssl", "3.0.11", "OpenSSL Foundation", "Apache-2.0"),
            ("etcd", "3.5.9", "CNCF", "Apache-2.0"),
            ("grpc", "1.59.2", "Google LLC", "Apache-2.0"),
            ("erasure-codes", "0.0.3", "MinIO Inc", "Apache-2.0"),
        ],
    },
    {
        "name": "Portainer", "item_type": "application", "category": "Container Management",
        "manufacturer": "Portainer.io", "developer": "Portainer.io", "version": "2.19.4",
        "description": "Lightweight management UI for Docker and Kubernetes",
        "components": [
            ("golang", "1.21.3", "Google LLC", "BSD-3-Clause"),
            ("angular", "17.0.3", "Google LLC", "MIT"),
            ("docker", "24.0.7", "Docker Inc", "Apache-2.0"),
            ("bbolt", "1.3.8", "Ben Johnson", "MIT"),
            ("jwt-go", "3.2.0", "Dave Grijalva", "MIT"),
        ],
    },
    {
        "name": "Netdata", "item_type": "application", "category": "Monitoring",
        "manufacturer": "Netdata Inc", "developer": "Costa Tsaousis", "version": "1.43.2",
        "description": "Real-time performance monitoring for systems and applications",
        "components": [
            ("libuv", "1.47.0", "libuv contributors", "MIT"),
            ("openssl", "3.0.11", "OpenSSL Foundation", "Apache-2.0"),
            ("lz4", "1.9.4", "Yann Collet", "BSD-2-Clause"),
            ("judy", "1.0.5", "Doug Baskins", "LGPL-2.1"),
            ("libmosquitto", "2.0.17", "Roger Light", "EPL-2.0"),
            ("protobuf", "3.21.12", "Google LLC", "BSD-3-Clause"),
        ],
    },
]


def get_or_create_component(db, name, version, supplier, license_name):
    existing = (
        db.query(models.Component)
        .filter(
            models.Component.component_name == name,
            models.Component.version == version,
        )
        .first()
    )
    if existing:
        return existing
    component = models.Component(
        component_name=name,
        version=version,
        supplier=supplier,
        license=license_name,
    )
    db.add(component)
    db.commit()
    db.refresh(component)
    return component


def seed_public_catalog(db, admin_user_id: int):
    seeded = 0
    for item_data in REAL_ITEMS:
        existing = db.query(models.Item).filter(
            models.Item.name == item_data["name"],
            models.Item.source_format == "public_catalog",
        ).first()
        if existing:
            continue

        item = models.Item(
            user_id=admin_user_id,
            name=item_data["name"],
            item_type=item_data["item_type"],
            category=item_data["category"],
            manufacturer=item_data["manufacturer"],
            developer=item_data["developer"],
            version=item_data["version"],
            source_format="public_catalog",
            description=item_data["description"],
            owner=item_data["manufacturer"],
            source_name=item_data["name"],
            is_public=True,
            is_verified=True,
            approval_status="approved",
        )
        db.add(item)
        db.commit()
        db.refresh(item)

        for comp_name, comp_version, comp_supplier, comp_license in item_data["components"]:
            component = get_or_create_component(
                db, comp_name, comp_version, comp_supplier, comp_license
            )
            existing_link = db.query(models.ItemComponent).filter(
                models.ItemComponent.item_id == item.id,
                models.ItemComponent.component_id == component.id,
            ).first()
            if not existing_link:
                db.add(models.ItemComponent(item_id=item.id, component_id=component.id))
                db.commit()

        seeded += 1

    return seeded